# Generated by Django 4.2.3 on 2023-07-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.google.com/imgres?imgurl=https%3A%2F%2Fplatform.foodi-menus.com%2Fstatic%2Fmedia%2Fplaceholder_food.91ea4630.png&tbnid=ZlkReMRdt9AFrM&vet=12ahUKEwi4usqO9qyAAxWtumMGHSK6BrIQMygNegUIARDeAQ..i&imgrefurl=https%3A%2F%2F82ndaveba.com%2Ftaqueria-el-torito%2F&docid=7RocrfNwect6DM&w=860&h=900&q=placeholder%20image%20for%20food&ved=2ahUKEwi4usqO9qyAAxWtumMGHSK6BrIQMygNegUIARDeAQ",
                max_length=1000,
            ),
        ),
    ]
