# Generated by Django 4.2.3 on 2023-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2FfriedRice.html&psig=AOvVaw3bo40h87K4yQFhxXHtj6UJ&ust=1690480342652000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCMCwnJX4rIADFQAAAAAdAAAAABAD",
                max_length=1000,
            ),
        ),
    ]
