# Generated by Django 4.2.4 on 2023-08-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_item_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://i0.wp.com/servedcatering.com/wp-content/uploads/2021/05/menu-item-placeholder.png?ssl=1",
                max_length=200,
            ),
        ),
    ]
